add advice on `load-theme' to apply `circadian-enable-theme'
guidoschmidt/circadian.el pull request #12
Opened 2018-01-24 07:43 UTC by stardiviner

This is useful for user when they want to manually switch color-theme with `load-theme`.

2018-02-23 07:24 UTC, guidoschmidt requested changes

2018-02-23 07:24 UTC, guidoschmidt commented on circadian.el
> +  (enable-theme theme)
First of all: sorry for the late answer 🙂 

Correct me if I'm wrong, but this change completely breaks circadian's intended beahaviour as `enable-theme` would only load themes that have been loaded before in the current Emacs session (https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html).

As far as I understood your code proposal, you'd like to have an interactive command to load themes via circadian? I'd rather make `circadian-enable-theme` interactive and provide a prompt for selecting a theme.

Moreover it would be a good idea to check, if the designated theme in `circadian-enable-theme` was loaded before und if that's the case, rather use `enable-theme` than `load-theme` 🙂 If you'd like improve your proposal I'll be happy to accept the PR later on. Otherwise thank's for pointing me to the existance of `enable-theme` 👍

2018-05-16 21:48 UTC, closed without merging

2018-05-16 21:50 UTC, guidoschmidt commented
I'm closing this PR, as I'm using `enable-theme` or `counsel-load-theme` when I manually want to switch Emacs themes.

2018-05-16 23:36 UTC, stardiviner commented
Sure. :)